services:
  
  helpdeskservice:
    ports:
      - "3000:80"
    volumes:
      - ${PWD}/backend/src/helpdesk_service:/app
      - ${PWD}/backend/src/common:/app/app/common
      - ${PWD}/data:/app/data
    env_file:
      - .env
    environment:
      - HOST_PROJECT_ROOT=${PWD}
      - TZ=Asia/Kolkata
    networks:
      - it-support-dev

  usermanagementservice:
    ports:
      - "3001:80"
    volumes:
      - ${PWD}/backend/src/usermanagementservice:/app
      - ${PWD}/backend/src/common:/app/app/common
      - ${PWD}/data:/app/data
    env_file:
      - .env
    environment:
      - HOST_PROJECT_ROOT=${PWD}
      - TZ=Asia/Kolkata
    networks:
      - it-support-dev

  postgresdb:
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgresdb-data:/var/lib/postgresql/data/pgdata
      - ./db/init:/docker-entrypoint-initdb.d/
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - it-support-dev
  
  ngrok:
    ports:
      - "4040:4040"
    env_file:
      - .env
    environment:
      NGROK_AUTHTOKEN: '${NGROK_AUTH_TOKEN}'
    networks:
      - it-support-dev

networks:
  it-support-dev:
    driver: bridge

volumes:
  postgresdb-data:
   name: itsupport_postgresdb_data
   labels:
    keep: true