services:
  helpdeskservice:
    image: '${DOCKER_HELPDESKSERVICE}'
    container_name: '${DOCKER_HELPDESKSERVICE}'
    build:
      context: ${PWD}/backend/src
      dockerfile: helpdesk_service/helpdesk_service.dockerfile
    restart: always
    depends_on:
      - ngrok

  usermanagementservice:
    image: '${DOCKER_USERMANAGEMENTSERVICE}'
    container_name: '${DOCKER_USERMANAGEMENTSERVICE}'
    build:
      context: ${PWD}/backend/src
      dockerfile: usermanagementservice/usermanagementservice.dockerfile
    restart: always

  postgresdb:
    image: pgvector/pgvector:pg15
    container_name: '${DOCKER_POSTGRESDB}'
    restart: always

  ngrok:
    image: ngrok/ngrok:alpine
    restart: always
    command: http helpdeskservice:80 --log=stdout