# generated by datamodel-codegen:
#   filename:  usermanagement.yaml
#   timestamp: 2024-12-24T10:11:49+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, EmailStr, Field, constr


class SignUpRequest(BaseModel):
    first_name: constr(min_length=1) = Field(..., description='First Name')
    last_name: constr(min_length=1) = Field(..., description='Last Name')
    email: EmailStr = Field(..., description='Email')
    password: constr(min_length=1) = Field(..., description='Password')


class TokenResponse(BaseModel):
    token: Optional[str] = Field(None, description='JWT Token')
    token_type: Optional[str] = Field(None, description='Token Type')


class SignInRequest(BaseModel):
    email: EmailStr = Field(..., description='email of the user')
    password: constr(min_length=1) = Field(..., description='password')
